# Generated by Django 4.1.4 on 2022-12-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_note_content_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
