# Generated by Django 4.1.4 on 2022-12-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_note_options_note_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['updated_at']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='pinned',
            new_name='p',
        ),
    ]
