# Generated by Django 4.1.4 on 2022-12-22 14:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
