# Generated by Django 4.1.4 on 2022-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark',
            field=models.BooleanField(default=False),
        ),
    ]
